// <auto-generated />
namespace LibraryApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class UniDBSchema3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UniDBSchema3));
        
        string IMigrationMetadata.Id
        {
            get { return "202106281418157_UniDB Schema3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
